### PR TITLE
fix setup error for mac

### LINKED ISSUE #92: Cross platform ernest installer
Actually when you run the ernestio/ernest setup on mac you get an annoying:
```
#################
Ernest Setup Tool
#################

Checking Prerequisites

Please enter in the hostname you wish ernest to run as
dernest.local
Generating a 4096 bit RSA private key
................++
.......................................................................................................................................................................................................++
writing new private key to './config/nginx/ernest.key'
-----
sed: 1: "./config/nginx/ernest.l ...": invalid command code .
```
This is mainly because sed works different on mac.

Explore alternatives in order to make the installer compatible with different platforms.

### PR DESCRIPTION
**Pull request by rawgni**
close #92

### CODE REVIEW

**Comment by adriacidre** [comment]
Ty @rawgni we will review it asap :)

**Comment by rawgni** [comment]
@adriacidre would probably be better if we are not doing a in-place replacement, instead using a template. With in-place, the change of `ERNESTHOST` through setup only work once. 

maybe do something like :
`sed -e s/ERNESTHOST/$ERNESTHOST/g' ./config/nginx/ernest.local.tmpl > ./config/nginx/ernest.local`

**Comment by adriacidre** [comment]
@rawgni sounds perfect to me, please go ahead :)

**Comment by rawgni** [comment]
can't seem to re-open the PR, resubmit #96

**Pull request closed without merging**
